###
# Copyright (2017) Hewlett Packard Enterprise Development LP
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
### 
---
- name: Install Load Balancers
  hosts: loadbalancer
  gather_facts: false
  become_user: root
  become: true

  vars_files:
    - ../group_vars/vars
    - includes/internal_vars.yml

  environment: "{{ env }}"

  tasks:

    - set_fact: 
        open_ports: "{{ internal_dtr_lb_ports | union (internal_ucp_lb_ports) | union ( internal_worker_lb_ports ) }}"

    - name: Open ports  in the firewall
      firewalld:
        port: "{{ item }}"
        immediate: true
        permanent: true
        state: enabled
      with_items: "{{ open_ports }}"

    - name: Add rule for vrrp protocole
      firewalld:
        rich_rule: 'rule protocol value="vrrp" accept'
        immediate: true
        permanent: true
        state: enabled

    - name: Install Required Pkgs for seboolean module
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - libsemanage-python
        - libselinux-python

    - name: Install haproxy and keepalived
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - psmisc
        - haproxy
        - keepalived

    - name: Enable HAPROXY to open non standard ports
      seboolean:
        name: haproxy_connect_any
        state: yes
        persistent: yes

    - name: Allow binding on remote IPs
      sysctl:
        name: net.ipv4.ip_nonlocal_bind
        value: 1
        state: present

    - name: Allow routing
      sysctl:
        name: net.ipv4.ip_forward
        value: 1
        state: present

    - name: Update haproxy.cfg
      template:
        src: ../templates/lbs/haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
        owner: root
        group: root
        mode: 0644        
      notify: Enable and start haproxy service

    - name: Enable and start haproxy service
      systemd:
        name: haproxy
        enabled: yes
        state: started

    - name: Update keepalived.conf
      template:
        src: ../templates/lbs/keepalived.conf.j2
        dest: /etc/keepalived/keepalived.conf
        owner: root
        group: root
        mode: 0644        
      notify: Enable and start keepalived service

    - name: Enable and start keepalived service
      systemd:
        name: keepalived
        enabled: yes
        state: started

  handlers:

    - name: Enable and start haproxy service
      systemd:
        name: haproxy
        enabled: yes
        state: restarted

    - name: Enable and start keepalived service
      systemd:
        name: keepalived
        enabled: yes
        state: restarted

