networks:
  - name:  '{{ vm_portgroup }}'
    ip:  "{{ ip_addr | ipaddr('address') }}"
    netmask: "{{ ip_addr | ipaddr('netmask') }}"
    gateway: "{{ gateway }}"

# public network
  - name: 'netExternal'
    ip:  "{{ external_addr | ipaddr('address') }}"
    netmask: "{{ external_addr | ipaddr('netmask') }}"

disks_specs:
  - size_gb:  '{{ disk1_size }}'
    type: thin
    datastore: "{{ datastores | random }}"

