###
# Copyright (2017) Hewlett Packard Enterprise Development LP
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###
---
k8s: "{{ k8s_enabled | default('true') }}"

ucp_certificates_volume_name: 'ucp-controller-server-certs'

internal_ucpk8s_ports:
  - 179/tcp
  - 443/tcp
  - 2376/tcp
  - 2377/tcp
  - 4789/udp
  - 6443/tcp
  - 6444/tcp
  - 7946/tcp
  - 7946/udp
  - 10250/tcp
  - 12376/tcp
  - 12378/tcp
  - 12379-12387/tcp

internal_ucp200_ports:
  - 443/tcp
  - 2376/tcp
  - 2377/tcp
  - 4789/udp
  - 7946/tcp
  - 7946/udp
  - 12376/tcp
  - 12379-12387/tcp

internal_dtrk8s_ports:
  - 80/tcp
  - 443/tcp
  - 179/tcp
  - 4789/udp
  - 6444/tcp
  - 7946/tcp
  - 7946/udp
  - 10250/tcp
  - 12376/tcp
  - 12378/tcp

internal_dtr200_ports:
  - 80/tcp
  - 443/tcp
  - 2377/tcp
  - 4789/udp
  - 7946/tcp
  - 7946/udp
  - 12376/tcp

internal_wrk200_ports:
  - 443/tcp
  - 2377/tcp
  - 4789/udp
  - 7946/tcp
  - 7946/udp
  - 12376/tcp

internal_wrkk8s_ports:
  - 179/tcp
  - 4789/udp
  - 6444/tcp
  - 7946/tcp
  - 7946/udp
  - 10250/tcp
  - 12376/tcp
  - 12378/tcp
 

internal_ucp_ports:
  "{% if k8s == 'true' %}{{ internal_ucpk8s_ports }}{% else %}{{  internal_ucp200_ports }}{% endif %}"

internal_worker_ports:
  "{% if k8s == 'true' %}{{ internal_wrkk8s_ports }}{% else %}{{  internal_wrk200_ports }}{% endif %}"

internal_dtr_ports:
  "{% if k8s == 'true' %}{{ internal_dtrk8s_ports }}{% else %}{{  internal_dtr200_ports }}{% endif %}"

internal_syslog_ports:
  - 514/tcp
  - 514/udp


internal_ucp200_lb_ports:
  - 80/tcp
  - 443/tcp

internal_ucpk8s_lb_ports:
  - 80/tcp
  - 443/tcp
  - 6443/tcp

internal_ucp_lb_ports: 
  "{% if k8s == 'true' %}{{ internal_ucpk8s_lb_ports }}{% else %}{{ internal_ucp200_lb_ports }}{% endif %}"

internal_dtr_lb_ports:
  - 80/tcp
  - 443/tcp

internal_worker_lb_ports:
  - 80/tcp
  - 443/tcp

#
# if new-style load balancers are wanted, they take precedence over the old-style singleton load balancers once specified with ucp_lb, dtr_lb and worker_lb
#
ucp_lb_fqdn_legacy: "{% if groups.ucp_lb is defined and groups.ucp_lb | length > 0 %}{{ groups.ucp_lb[0] }}.{{ domain_name }}{% endif %}"
ucp_lb_fqdn_vrrp: "{% if loadbalancers is defined and loadbalancers.ucp is defined %}{{ loadbalancers.ucp.public_fqdn }}{% endif %}"
ucp_lb_fqdn: "{% if ucp_lb_fqdn_vrrp | length > 0 %}{{ ucp_lb_fqdn_vrrp }}{% else %}{{ ucp_lb_fqdn_legacy }}{% endif %}"

ucp_lb_ipv4_legacy: "{% if groups.ucp_lb is defined and groups.ucp_lb | length > 0 %}{{ hostvars[groups.ucp_lb[0]].ip_addr | ipaddr('address') }}{% endif %}"
ucp_lb_ipv4_vrrp: "{% if loadbalancers is defined and loadbalancers.ucp is defined %}{{ loadbalancers.ucp.public_vip }}{% endif %}"
ucp_lb_ipv4: "{% if ucp_lb_ipv4_vrrp | length > 0 %}{{ ucp_lb_ipv4_vrrp }}{% else %}{{ ucp_lb_ipv4_legacy }}{% endif %}"

dtr_lb_fqdn_legacy: "{% if groups.dtr_lb is defined and groups.dtr_lb | length > 0 %}{{ groups.dtr_lb[0] }}.{{ domain_name }}{% endif %}"
dtr_lb_fqdn_vrrp: "{% if loadbalancers is defined and loadbalancers.dtr is defined %}{{ loadbalancers.dtr.public_fqdn }}{% endif %}"
dtr_lb_fqdn: "{% if dtr_lb_fqdn_vrrp | length > 0 %}{{ dtr_lb_fqdn_vrrp }}{% else %}{{ dtr_lb_fqdn_legacy }}{% endif %}"

